name: username_gen
description: A new Flutter package project.
version: 1.0.0-nullsafety.2
homepage: https://github.com/Zfinix/username_gen

environment:
  sdk: '>=2.10.0-0 <2.12.0'

dependencies:
  test: ^1.16.0-nullsafety.7
  

