name: username_gen
description: This is a simple package to create random usernames. To user it simply make these commands
version: 1.0.4
homepage: https://github.com/Zfinix/username_gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.3
  

